"""Render a finished run as a Markdown report (for docs, tickets, or chat)."""

from app.domain import ImplementationPlan, MeetingAnalysis, SourceReference
from app.runs import Run


def render_markdown(run: Run) -> str:
    lines: list[str] = [f"# {run.title}", ""]
    created = run.created_at.strftime("%Y-%m-%d %H:%M UTC")
    lines += [f"_Generated by Planar on {created}._", ""]
    if run.warnings:
        lines += ["> **Warnings**"]
        lines += [f"> - {warning}" for warning in run.warnings]
        lines.append("")
    if run.analysis is not None:
        lines += _analysis(run.analysis)
    if run.plan is not None:
        lines += _plan(run.plan)
    return "\n".join(lines).rstrip() + "\n"


def _cite(ref: SourceReference) -> str:
    where = ""
    if ref.line_start is not None:
        where = f"L{ref.line_start}"
        if ref.line_end and ref.line_end != ref.line_start:
            where += f"–{ref.line_end}"
    who = f"{ref.speaker}, " if ref.speaker else ""
    head = f"{who}{where}".strip(", ")
    prefix = f"({head}) " if head else ""
    return f"  > {prefix}“{ref.excerpt}”"


def _links(label: str, ids: list[str]) -> str:
    return f"  - {label}: {', '.join(ids)}" if ids else ""


def _analysis(analysis: MeetingAnalysis) -> list[str]:
    out: list[str] = []

    def section(title: str, count: int) -> None:
        out.extend([f"## {title} ({count})", ""])

    section("Decisions", len(analysis.decisions))
    for item in analysis.decisions:
        out += [f"- **{item.id}** {item.statement}", _cite(item.source_reference), ""]

    section("Requirements", len(analysis.requirements))
    for item in analysis.requirements:
        out += [f"- **{item.id}** {item.statement}"]
        out += [x for x in (_links("From", item.related_decision_ids),
                            _links("Risks", item.related_risk_ids)) if x]
        out += [_cite(item.source_reference), ""]

    section("Tasks", len(analysis.tasks))
    for item in analysis.tasks:
        meta = [item.priority.value]
        if item.owner:
            meta.append(f"owner: {item.owner}")
        if item.due:
            meta.append(f"due: {item.due}")
        out += [f"- [ ] **{item.id}** {item.title} _({'; '.join(meta)})_"]
        if item.description and item.description != item.title:
            out.append(f"  {item.description}")
        for criterion in item.acceptance_criteria:
            out.append(f"  - Done when: {criterion}")
        link = _links("Implements", item.related_requirement_ids)
        if link:
            out.append(link)
        out += [_cite(ref) for ref in item.source_references]
        out.append("")

    section("Risks", len(analysis.risks))
    for item in analysis.risks:
        out += [f"- **{item.id}** [{item.severity.value}] {item.description}"]
        link = _links("Affects", item.related_requirement_ids)
        if link:
            out.append(link)
        out += [_cite(item.source_reference), ""]

    section("Open questions", len(analysis.open_questions))
    for item in analysis.open_questions:
        out += [f"- **{item.id}** {item.question}", f"  {item.context}"]
        out += [_cite(item.source_reference), ""]
    return out


def _plan(plan: ImplementationPlan) -> list[str]:
    out = [f"## Implementation plan: {plan.title}", "", plan.summary, ""]
    for index, step in enumerate(plan.steps, start=1):
        refs = step.related_requirement_ids + step.related_task_ids
        suffix = f" _({', '.join(refs)})_" if refs else ""
        out += [f"{index}. **{step.title}**{suffix}", f"   {step.description}"]
    if plan.acceptance_criteria:
        out += ["", "### Done when", ""]
        out += [f"- [ ] {criterion}" for criterion in plan.acceptance_criteria]
    out.append("")
    return out
