"""Render a finished run as a Markdown report (for docs, tickets, or chat)."""

import re

from app.domain import ImplementationPlan, MeetingAnalysis, SourceReference
from app.runs import Run


def render_markdown(run: Run) -> str:
    lines: list[str] = [f"# {run.title}", ""]
    created = run.created_at.strftime("%Y-%m-%d %H:%M UTC")
    lines += [f"_Generated by Planar on {created}._", ""]
    if run.warnings:
        lines += ["> **Warnings**"]
        lines += [f"> - {warning}" for warning in run.warnings]
        lines.append("")
    if run.analysis is not None:
        lines += _analysis(run.analysis)
    if run.plan is not None:
        lines += _plan(run.plan)
        if run.analysis is not None and run.plan.steps:
            lines += plan_map_mermaid(run.analysis, run.plan)
    return "\n".join(lines).rstrip() + "\n"


def _cite(ref: SourceReference) -> str:
    where = ""
    if ref.line_start is not None:
        where = f"L{ref.line_start}"
        if ref.line_end and ref.line_end != ref.line_start:
            where += f"–{ref.line_end}"
    who = f"{ref.speaker}, " if ref.speaker else ""
    head = f"{who}{where}".strip(", ")
    prefix = f"({head}) " if head else ""
    return f"  > {prefix}“{ref.excerpt}”"


def _links(label: str, ids: list[str]) -> str:
    return f"  - {label}: {', '.join(ids)}" if ids else ""


def _analysis(analysis: MeetingAnalysis) -> list[str]:
    out: list[str] = []

    def section(title: str, count: int) -> None:
        out.extend([f"## {title} ({count})", ""])

    section("Decisions", len(analysis.decisions))
    for item in analysis.decisions:
        out += [f"- **{item.id}** {item.statement}", _cite(item.source_reference), ""]

    section("Requirements", len(analysis.requirements))
    for item in analysis.requirements:
        out += [f"- **{item.id}** {item.statement}"]
        out += [x for x in (_links("From", item.related_decision_ids),
                            _links("Risks", item.related_risk_ids)) if x]
        out += [_cite(item.source_reference), ""]

    section("Tasks", len(analysis.tasks))
    for item in analysis.tasks:
        meta = [item.priority.value]
        if item.owner:
            meta.append(f"owner: {item.owner}")
        if item.due:
            meta.append(f"due: {item.due}")
        out += [f"- [ ] **{item.id}** {item.title} _({'; '.join(meta)})_"]
        if item.description and item.description != item.title:
            out.append(f"  {item.description}")
        for criterion in item.acceptance_criteria:
            out.append(f"  - Done when (suggested): {criterion}")
        link = _links("Implements", item.related_requirement_ids)
        if link:
            out.append(link)
        out += [_cite(ref) for ref in item.source_references]
        out.append("")

    section("Risks", len(analysis.risks))
    for item in analysis.risks:
        out += [f"- **{item.id}** [{item.severity.value}] {item.description}"]
        link = _links("Affects", item.related_requirement_ids)
        if link:
            out.append(link)
        out += [_cite(item.source_reference), ""]

    section("Open questions", len(analysis.open_questions))
    for item in analysis.open_questions:
        out += [f"- **{item.id}** {item.question}", f"  {item.context}"]
        out += [_cite(item.source_reference), ""]
    return out


def _plan(plan: ImplementationPlan) -> list[str]:
    out = [f"## Implementation plan: {plan.title}", "", plan.summary, ""]
    for index, step in enumerate(plan.steps, start=1):
        refs = step.related_decision_ids + step.related_requirement_ids + step.related_task_ids
        suffix = f" _({', '.join(refs)})_" if refs else ""
        when = f" · {step.when}" if step.when else ""
        out += [f"{index}. **{step.title}**{when}{suffix}", f"   {step.description}"]
    if plan.acceptance_criteria:
        out += ["", "### Done when", ""]
        out += [f"- [ ] {criterion}" for criterion in plan.acceptance_criteria]
    out.append("")
    return out


_MAX_LABEL_CHARS = 48


def _node_id(item_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", item_id)


def _label(text: str) -> str:
    text = " ".join(text.split())
    if len(text) > _MAX_LABEL_CHARS:
        text = text[: _MAX_LABEL_CHARS - 1].rstrip() + "…"
    return text.replace('"', "#quot;")


def plan_map_mermaid(analysis: MeetingAnalysis, plan: ImplementationPlan) -> list[str]:
    """The plan map as a Mermaid flowchart: decisions -> requirements -> steps -> owners.

    Renders as a diagram on GitHub, GitLab, Notion, Obsidian and most Markdown
    viewers. Built from the validated record, so every arrow is a real link.
    """
    requirements = {r.id: r for r in analysis.requirements}
    decisions = {d.id: d for d in analysis.decisions}
    tasks = {t.id: t for t in analysis.tasks}
    edges: list[tuple[str, str]] = []

    def link(a: str, b: str) -> None:
        if (a, b) not in edges:
            edges.append((a, b))

    req_ids: list[str] = []
    dec_ids: list[str] = []
    owners: list[str] = []
    for step in plan.steps:
        for req_id in step.related_requirement_ids:
            if req_id in requirements:
                if req_id not in req_ids:
                    req_ids.append(req_id)
                link(req_id, step.id)
        for dec_id in step.related_decision_ids:
            if dec_id in decisions:
                if dec_id not in dec_ids:
                    dec_ids.append(dec_id)
                link(dec_id, step.id)
        for task_id in step.related_task_ids:
            task = tasks.get(task_id)
            if task is None:
                continue
            owner = task.owner or "Unassigned"
            if owner not in owners:
                owners.append(owner)
            link(step.id, f"owner:{owner}")
    for req_id in req_ids:
        for dec_id in requirements[req_id].related_decision_ids:
            if dec_id in decisions:
                if dec_id not in dec_ids:
                    dec_ids.append(dec_id)
                link(dec_id, req_id)

    def node(key: str) -> str:
        return _node_id(key.replace("owner:", "OWNER_"))

    out = ["## Plan map", "", "```mermaid", "flowchart LR"]
    if dec_ids:
        out.append('  subgraph why["Decisions"]')
        out += [f'    {node(d)}["{d}: {_label(decisions[d].statement)}"]' for d in dec_ids]
        out.append("  end")
    if req_ids:
        out.append('  subgraph what["Requirements"]')
        out += [f'    {node(r)}["{r}: {_label(requirements[r].statement)}"]' for r in req_ids]
        out.append("  end")
    out.append('  subgraph how["Plan steps"]')
    out += [
        f'    {node(step.id)}["{i}. {_label(step.title)}'
        + (f"<br/><i>{_label(step.when)}</i>" if step.when else "")
        + '"]'
        for i, step in enumerate(plan.steps, start=1)
    ]
    out.append("  end")
    if owners:
        out.append('  subgraph who["Owners"]')
        out += [f'    {node("owner:" + o)}(["{_label(o)}"])' for o in owners]
        out.append("  end")
    out += [f"  {node(a)} --> {node(b)}" for a, b in edges]
    out += ["```", ""]
    unlinked = len(decisions) - len(dec_ids)
    if unlinked > 0:
        out += [f"_{unlinked} other decision(s) apply to the plan as a whole._", ""]
    return out
